language: python
python:
  - "2.7"
env:
  - TOX_ENV=py2.7-django1.6 WEBTEST_DRIVER="PhantomJS"
  - TOX_ENV=py3.3-django1.6 WEBTEST_DRIVER="PhantomJS"
  - TOX_ENV=flake8
install:
  - pip install tox==1.7.0
script:
  - tox -e $TOX_ENV
